### PR TITLE
Remove sleep

### PR DESCRIPTION
**Pull request by soilSpoon**

### CODE REVIEW

**Comment by lukeraymonddowning** [comment]
@soilSpoon if possible, can you give your reasoning behind this change?

**Comment by soilSpoon** [comment]
> @soilSpoon if possible, can you give your reasoning behind this change?

@lukeraymonddowning There seems to be no need to sleep, and if there are many test cases, the speed is adversely affected.

May I know the reason why you put sleep?

**Comment by lukeraymonddowning** [comment]
@soilSpoon the call to sleep was taken directly from Paratest. Do you have any benchmarks that could show the difference in speed?

**Comment by nunomaduro** [comment]
I rather not apply custom changes to code that was copied from Paratest. Please pull request this change to paratest first.

**Pull request closed without merging**
